spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate.ddl-auto: create-drop
    hibernate.format.sql: true
    show-sql: true

  artemis:
    mode: embedded
    embedded:
      queues: created.queue,post.find.queue,post.ok.queue,failed.queue,comments.find.queue,comments.ok.queue